name: trigger-netlify-build

on:
  schedule:
#     - cron: '0 19 * * *' # At 1pm est
  - cron: '15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Curl request
      run: curl -s -X POST "https://api.netlify.com/build_hooks/${TOKEN}"
      env:
        TOKEN: ${{ secrets.NETLIFY_CRON_BUILD_HOOK }}
